image:
  name: python:3.10

stages:
  - Check-source
  - Tests
  - Build


check-source:
  stage: Check-source
  before_script:
    - pip install -r requirements_dev.txt
  script:
    - flake8 src
    - mypy src
    - vulture src
    - bandit src
    - safety check -r requirements.txt
    - safety check -r requirements_dev.txt
    - semgrep --config auto
  allow_failure: True

test-python:
  stage: Tests
  before_script:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt
  variables:
    PYTHONPATH: .
  artifacts:
    paths:
      - reports/pytest/cov_html
  script:
    - pytest --cov=src --cov-report=html:reports/pytest/cov_html

package-code:
  stage: Build
  before_script:
    - pip install build
  script:
    - python -m build --wheel
  artifacts:
    paths:
      - dist/src-0-py3-none-any.whl
