stages:
  - build
  - test

variables:
  LANG: "en_US.UTF-8"

before_script:
  - cd /Users/leo.babonnaud/octo_mission/ci_python
  - source venv/bin/activate

build:
  stage: build
  script:
    - touch fichier_ci_demo.csv
  tags:
    - mymac

test:
  stage: test
  script:
    - touch fichier_ci_demo2.csv
  tags:
    - mymac