stages:
  - build
  - test

variables:
  LANG: "en_US.UTF-8"

before_script:
  - pip install pandas

build:
  stage: build
  script:
    - touch fichier_ci_demo.csv
  tags:
    - mymac

test:
  stage: test
  script:
    - touch fichier_ci_demo2.csv
  tags:
    - mymac